version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  spring-boot-app:
    build:
      context: ./spring-boot-server  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile         # Name of the Dockerfile
    image: yosrimlik/jenkins-exam-backend:latest
    container_name: spring-boot-app
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/testdb?serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
    depends_on:
      - mysql-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge